databases:
  - name: backenddb
    plan: free
    databaseName: backend
    user: backend

services:
  - type: web
    plan: free
    name: backend
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker --workers ${WEB_CONCURRENCY} --timeout 60'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backenddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
